version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    dev-tooling:
      patterns:
      - "@biomejs/*"
      - "@types/*"
      - "publint"
      - "@arethetypeswrong/*"
      - "vitest"
      - "typescript"
  open-pull-requests-limit: 5

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 5
